"""Write LLM analysis results into a Markdown note.

This module converts the structured JSON generated by `scripts/llm_analyzer.py`
into a readable Markdown note.

Design goal:
- Keep the output simple and durable
- Use a reusable Markdown template file instead of hard-coding the note layout
- Preserve useful metadata such as paper title, source file, figures, and notes

Typical flow:
    1. Run `scripts/pdf_parser.py` to extract the raw paper JSON
    2. Run `scripts/llm_analyzer.py` to generate structured analysis JSON
    3. Run this script to write a Markdown note into your notes folder
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Sequence

# Match figure references in text like "如图4所示", "Figure 5", "见图 3"
_FIG_REF_RE = re.compile(
    r"(?:如|见|参见|参考)?(?:Figure|Fig\.?|图)\s*(\d+)",
    re.IGNORECASE,
)


@dataclass
class ObsidianNote:
    """A small container for note metadata and rendered Markdown."""

    title: str
    markdown: str
    path: Path


_SKILL_ROOT = Path(__file__).resolve().parent.parent
TEMPLATE_PATH = _SKILL_ROOT / "assets" / "paper-note.md"


def load_template(path: str | Path = TEMPLATE_PATH) -> str:
    """Read the note template file."""
    return Path(path).read_text(encoding="utf-8")


def load_json(path: str | Path) -> dict[str, Any]:
    """Read a JSON file and return a dict."""
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9\u4e00-\u9fff]+", "_", text.strip().lower()).strip("_")
    return slug or "paper_note"


def _format_bullets(items: Any) -> str:
    """Format a list into Markdown bullet points.

    If the input is an empty list, return a placeholder to avoid blank blocks.
    """
    if not items:
        return "- 无"
    if isinstance(items, str):
        return f"- {items}"
    if not isinstance(items, list):
        return f"- {str(items)}"
    return "\n".join(f"- {str(item)}" for item in items)


def _format_text(value: Any) -> str:
    """Convert any value to Markdown-appropriate text."""
    if value is None:
        return "（待补充）"
    if isinstance(value, list):
        return "\n\n".join(str(item) for item in value) if value else "（待补充）"
    if isinstance(value, dict):
        # LLM sometimes outputs dict-formatted experiments, convert to markdown list
        parts: list[str] = []
        for k, v in value.items():
            if isinstance(v, list):
                bullet_items = "\n".join(f"  - {item}" for item in v)
                parts.append(f"- **{k}:**\n{bullet_items}")
            else:
                parts.append(f"- **{k}:** {v}")
        return "\n".join(parts)
    text = str(value).strip()
    # Detect Python dict strings in LLM output (e.g. experiments field)
    if text.startswith("{") and text.endswith("}"):
        try:
            import ast
            parsed = ast.literal_eval(text)
            if isinstance(parsed, dict):
                return _format_text(parsed)
        except (ValueError, SyntaxError):
            pass
    return text if text else "（待补充）"


def _format_yaml_list(items: list[str]) -> str:
    """Format a string list into YAML array format (without outer quotes)."""
    if not items:
        return "  - "
    return "\n".join(f"  - {item}" for item in items)


def _clean_abstract(text: str) -> str:
    """Clean up PDF parsing artifacts in abstracts, like 'Jan\\n' prefix, hyphenation."""
    if not text:
        return ""
    # Remove leading month/year artifacts (e.g. "Jan\n", "2025\n")
    text = re.sub(r"^(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s*\n", "", text)
    text = re.sub(r"^\d{4}\s*\n", "", text)
    # Merge hyphenation breaks: applica-\ntions -> applications
    text = re.sub(r"(\w)-\s*\n\s*(\w)", r"\1\2", text)
    # Merge normal line breaks (not paragraph separators)
    text = re.sub(r"(?<!\n)\n(?!\n)", " ", text)
    # Collapse extra spaces
    text = re.sub(r"  +", " ", text)
    return text.strip()


def _embed_figure_images(
    text: str,
    images_dir: Path | None,
    attachments_dir: Path | None = None,
    max_images: int = 5,
) -> tuple[str, int]:
    """Scan text for figure number references, copy images to attachments dir and insert references.

    Returns (processed_text, number_of_embedded_images).
    """
    if not images_dir or not images_dir.is_dir():
        return text, 0

    # Build figure_number -> file_path mapping
    fig_map: dict[str, Path] = {}
    for img_file in sorted(images_dir.glob("*.png")):
        name = img_file.name.lower()
        m = re.search(r"figure[_\s-]*(\d+)", name)
        if m:
            fig_num = m.group(1)
            if fig_num not in fig_map:
                fig_map[fig_num] = img_file

    if not fig_map:
        return text, 0

    # Find all figure numbers referenced in text (deduplicated, in order)
    seen_figs: list[str] = []
    for m in _FIG_REF_RE.finditer(text):
        num = m.group(1)
        if num in fig_map and num not in seen_figs:
            seen_figs.append(num)

    if not seen_figs:
        return text, 0

    figs_to_embed = set(seen_figs[:max_images])

    # Copy images to attachments directory
    if attachments_dir:
        attachments_dir.mkdir(parents=True, exist_ok=True)
        for fig_num in figs_to_embed:
            src = fig_map[fig_num]
            dst = attachments_dir / src.name
            if not dst.exists():
                shutil.copy2(str(src), str(dst))

    # Insert image embeds after each reference (only once per figure)
    inserted: set[str] = set()
    lines = text.split("\n")
    new_lines: list[str] = []
    for line in lines:
        new_lines.append(line)
        for m in _FIG_REF_RE.finditer(line):
            num = m.group(1)
            if num in figs_to_embed and num not in inserted:
                img_path = fig_map[num]
                new_lines.append(f"\n![[{img_path.name}]]\n")
                inserted.add(num)

    return "\n".join(new_lines), len(inserted)


def _simplify_journal(journal: str) -> str:
    """Simplify long conference/journal names to short forms."""
    if not journal:
        return ""
    # Common conference short-name mapping
    short_names = {
        "Proceedings of the 31st ACM SIGKDD": "KDD",
        "Proceedings of the AAAI Conference": "AAAI",
        "International Conference on Learning Representations": "ICLR",
        "Neural Information Processing Systems": "NeurIPS",
        "International Conference on Machine Learning": "ICML",
        "International Joint Conference on Artificial Intelligence": "IJCAI",
        "The Web Conference": "WWW",
    }
    for prefix, short in short_names.items():
        if prefix.lower() in journal.lower():
            # Extract year suffix (e.g. '\'25, 2025)
            year_match = re.search(r"'?\d{2,4}", journal)
            year_suffix = year_match.group(0) if year_match else ""
            return f"{short} {year_suffix}".strip()
    return journal


def _render_template(template: str, variables: dict[str, str]) -> str:
    """Replace {{key | filter}} or {{key}} style placeholders with values.

    Templates may contain Obsidian/Templater style placeholders like:
      {{exportDate | format('YYYY-MM-DD')}}
      {{date | format('YYYY')}}
    We extract the key (ignoring filter) and look it up in variables.
    """
    def replacer(match: re.Match) -> str:
        inner = match.group(1).strip()
        # Extract key, ignore filter (e.g. `date | format('YYYY')` -> key is `date`)
        key = inner.split("|")[0].strip()
        return variables.get(key, match.group(0))

    # Match {{ ... }}, supporting single quotes, spaces and pipes
    pattern = re.compile(r"\{\{\s*(.+?)\s*\}\}")
    return pattern.sub(replacer, template)


def render_markdown(
    analysis: dict[str, Any],
    source_pdf: str,
    analysis_json: str,
    images_dir: str | Path | None = None,
    attachments_dir: str | Path | None = None,
) -> str:
    """Render Markdown from analysis JSON.

    This function fills the `paper-note.md` template with LLM structured results.
    """
    template = load_template()
    title = analysis.get("title") or analysis.get("paper") or Path(source_pdf).stem

    # Authors: prefer YAML array for frontmatter
    authors_raw = analysis.get("authors", [])
    if isinstance(authors_raw, str):
        authors_raw = [a.strip() for a in authors_raw.split(",") if a.strip()]
    elif isinstance(authors_raw, list) and len(authors_raw) == 1 and isinstance(authors_raw[0], str) and "," in authors_raw[0]:
        # LLM sometimes returns ["A, B, C"] instead of ["A", "B", "C"]
        authors_raw = [a.strip() for a in authors_raw[0].split(",") if a.strip()]
    authors_yaml = _format_yaml_list(authors_raw)
    authors_str = ", ".join(str(a) for a in authors_raw) if authors_raw else ""

    year = str(analysis.get("year", ""))
    current_date = datetime.now().strftime("%Y-%m-%d")

    summary = _format_text(analysis.get("summary"))
    tldr = _format_text(analysis.get("tldr"))
    problem = _format_text(analysis.get("problem"))
    method = _format_text(analysis.get("method"))
    result = _format_text(analysis.get("result"))
    architecture = _format_text(analysis.get("architecture"))
    innovations = _format_bullets(analysis.get("innovations"))
    experiments = _format_text(analysis.get("experiments"))
    thoughts = _format_text(analysis.get("thoughts"))
    figure_notes = _format_bullets(analysis.get("figure_notes"))

    # Auto-embed images: scan text for figure references, copy to attachments and insert
    _img_dir = Path(images_dir) if images_dir else None
    _att_dir = Path(attachments_dir) if attachments_dir else None
    architecture, _ = _embed_figure_images(architecture, _img_dir, _att_dir)
    experiments, _ = _embed_figure_images(experiments, _img_dir, _att_dir)
    limitations = _format_bullets(analysis.get("limitations"))

    # Prefer raw abstract, fallback to LLM summary
    abstract_raw = analysis.get("abstract", "")
    # Clean PDF parsing artifacts (e.g. "Jan\n" prefix, hyphenation app-\nlications)
    abstract_cleaned = _clean_abstract(abstract_raw)
    abstract_display = abstract_cleaned if abstract_cleaned else summary

    variables = {
        "title": str(title),
        "authors": authors_str,
        "authors_yaml": authors_yaml,
        "publicationTitle": _simplify_journal(str(analysis.get("journal", ""))),
        "citekey": str(analysis.get("citekey", "")),
        "zoteroSelectURI": str(analysis.get("zotero_link", "")),
        "url": "",
        "source_pdf": "",
        "analysis_json": analysis_json,
        "date": year,
        "abstractNote": abstract_display,
        "tldr": tldr,
        "problem": problem,
        "method": method,
        "result": result,
        "architecture": architecture,
        "innovations": innovations,
        "experiments": experiments,
        "thoughts": thoughts,
        "figure_notes": figure_notes,
        "limitations": limitations,
        "desktopURI": "",
        "exportDate": current_date,
        "topics": _format_yaml_list(analysis.get("topics", [])),
        "aliases": _format_yaml_list(analysis.get("aliases", [])),
        "related_papers": _format_yaml_list(analysis.get("related_papers", [])),
    }
    return _render_template(template, variables)


def write_obsidian_note(
    analysis_json_path: str | Path,
    vault_dir: str | Path,
    note_name: str | None = None,
    images_dir: str | Path | None = None,
    attachments_dir: str | Path | None = None,
) -> ObsidianNote:
    """Write LLM analysis result into a Markdown note.

    Parameters:
    - analysis_json_path: output file path from `llm_analyzer.py`
    - vault_dir: target directory for the final note
    - note_name: optional custom note filename; auto-generated from title if not provided
    - images_dir: optional source image directory; inferred from analysis_json sibling if not provided
    - attachments_dir: optional attachments directory; images are copied here for note references
    """
    analysis_json_path = Path(analysis_json_path)
    vault_dir = Path(vault_dir)
    vault_dir.mkdir(parents=True, exist_ok=True)

    analysis = load_json(analysis_json_path)
    source_pdf = str(analysis.get("paper", ""))

    # Infer image directory
    if images_dir is None:
        candidate = analysis_json_path.parent / "images" / "png"
        if candidate.is_dir():
            images_dir = candidate

    markdown = render_markdown(
        analysis=analysis,
        source_pdf=source_pdf,
        analysis_json=str(analysis_json_path),
        images_dir=images_dir,
        attachments_dir=attachments_dir,
    )

    title = analysis.get("title") or analysis.get("paper") or analysis_json_path.stem
    safe_name = note_name or _slugify(str(title))
    note_path = vault_dir / f"{safe_name}.md"
    note_path.write_text(markdown, encoding="utf-8")

    return ObsidianNote(title=str(title), markdown=markdown, path=note_path)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Write LLM analysis into a Markdown note")
    parser.add_argument("input", type=Path, help="Input analysis JSON from scripts/llm_analyzer.py")
    parser.add_argument("--vault", type=Path, required=True, help="Target directory for the note")
    parser.add_argument("--name", type=str, default=None, help="Optional note filename without extension")
    parser.add_argument("--images-dir", type=Path, default=None, help="Directory containing extracted figure PNGs")
    parser.add_argument("--attachments-dir", type=Path, default=None, help="Attachments directory to copy images into")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    note = write_obsidian_note(args.input, args.vault, args.name, args.images_dir, args.attachments_dir)
    print(json.dumps({"title": note.title, "path": str(note.path)}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
