"""Write LLM analysis results into an Obsidian-friendly Markdown note.

This module converts the structured JSON generated by `tools/llm_analyzer.py`
into a readable Markdown note that can be dropped directly into an Obsidian vault.

Design goal:
- Keep the output simple and durable
- Use a reusable Markdown template file instead of hard-coding the note layout
- Preserve useful metadata such as paper title, source file, figures, and notes

Typical flow:
    1. Run `tools/pdf_parser.py` to extract the raw paper JSON
    2. Run `tools/llm_analyzer.py` to generate structured analysis JSON
    3. Run this script to write a Markdown note into your Obsidian folder

说明：
- 这里不再把模板写死在代码里，而是直接读取 `templates/paper-note.md`
- 这样你以后只改模板文件，就能统一调整所有论文笔记的样式
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Sequence

# 匹配 LLM 正文中对图的引用，如 "如图4所示"、"Figure 5"、"见图 3"
_FIG_REF_RE = re.compile(
    r"(?:如|见|参见|参考)?(?:Figure|Fig\.?|图)\s*(\d+)",
    re.IGNORECASE,
)


@dataclass
class ObsidianNote:
    """A small container for note metadata and rendered Markdown."""

    title: str
    markdown: str
    path: Path


TEMPLATE_PATH = Path(__file__).resolve().parent.parent / "templates" / "paper-note.md"


def load_template(path: str | Path = TEMPLATE_PATH) -> str:
    """读取 Obsidian 模板文件。"""
    return Path(path).read_text(encoding="utf-8")


def load_json(path: str | Path) -> dict[str, Any]:
    """读取 JSON 文件并返回字典。"""
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9\u4e00-\u9fff]+", "_", text.strip().lower()).strip("_")
    return slug or "paper_note"


def _format_bullets(items: Any) -> str:
    """把列表格式化成 Markdown 项目符号。

    如果传进来的是空列表，就返回一个占位符，避免笔记里出现空白区块。
    """
    if not items:
        return "- 无"
    if isinstance(items, str):
        return f"- {items}"
    if not isinstance(items, list):
        return f"- {str(items)}"
    return "\n".join(f"- {str(item)}" for item in items)


def _format_text(value: Any) -> str:
    """把任意值转成适合 Markdown 段落显示的文本。"""
    if value is None:
        return "（待补充）"
    if isinstance(value, list):
        return "\n\n".join(str(item) for item in value) if value else "（待补充）"
    if isinstance(value, dict):
        # LLM 有时输出 dict 格式的 experiments，转成 markdown 列表
        parts: list[str] = []
        for k, v in value.items():
            if isinstance(v, list):
                bullet_items = "\n".join(f"  - {item}" for item in v)
                parts.append(f"- **{k}:**\n{bullet_items}")
            else:
                parts.append(f"- **{k}:** {v}")
        return "\n".join(parts)
    text = str(value).strip()
    # 检测 LLM 输出的 Python dict 字符串（如 experiments 字段）
    if text.startswith("{") and text.endswith("}"):
        try:
            import ast
            parsed = ast.literal_eval(text)
            if isinstance(parsed, dict):
                return _format_text(parsed)
        except (ValueError, SyntaxError):
            pass
    return text if text else "（待补充）"


def _format_yaml_list(items: list[str]) -> str:
    """把字符串列表格式化成 YAML 数组格式（不带外层引号）。"""
    if not items:
        return "  - "
    return "\n".join(f"  - {item}" for item in items)


def _clean_abstract(text: str) -> str:
    """清理 PDF 解析产生的摘要残影，如 'Jan\\n' 前缀、断行连字符等。"""
    if not text:
        return ""
    # 去掉开头的月份/年份残影（如 "Jan\n", "2025\n"）
    text = re.sub(r"^(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s*\n", "", text)
    text = re.sub(r"^\d{4}\s*\n", "", text)
    # 合并断行连字符：applica-\ntions → applications
    text = re.sub(r"(\w)-\s*\n\s*(\w)", r"\1\2", text)
    # 合并普通断行（非段落分隔）
    text = re.sub(r"(?<!\n)\n(?!\n)", " ", text)
    # 压缩多余空格
    text = re.sub(r"  +", " ", text)
    return text.strip()


def _embed_figure_images(
    text: str,
    images_dir: Path | None,
    attachments_dir: Path | None = None,
    max_images: int = 5,
) -> tuple[str, int]:
    """扫描正文中的图号引用，复制图片到 Obsidian 附件目录并插入引用。

    返回 (处理后的文本, 嵌入的图片数量)。
    """
    if not images_dir or not images_dir.is_dir():
        return text, 0

    # 建立图号 → 文件路径的映射
    fig_map: dict[str, Path] = {}
    for img_file in sorted(images_dir.glob("*.png")):
        name = img_file.name.lower()
        m = re.search(r"figure[_\s-]*(\d+)", name)
        if m:
            fig_num = m.group(1)
            if fig_num not in fig_map:
                fig_map[fig_num] = img_file

    if not fig_map:
        return text, 0

    # 找出正文中引用的所有图号（按出现顺序去重）
    seen_figs: list[str] = []
    for m in _FIG_REF_RE.finditer(text):
        num = m.group(1)
        if num in fig_map and num not in seen_figs:
            seen_figs.append(num)

    if not seen_figs:
        return text, 0

    figs_to_embed = set(seen_figs[:max_images])

    # 复制图片到 Obsidian 附件目录
    if attachments_dir:
        attachments_dir.mkdir(parents=True, exist_ok=True)
        for fig_num in figs_to_embed:
            src = fig_map[fig_num]
            dst = attachments_dir / src.name
            if not dst.exists():
                shutil.copy2(str(src), str(dst))

    # 在每个引用位置后插入图片嵌入（只插一次）
    inserted: set[str] = set()
    lines = text.split("\n")
    new_lines: list[str] = []
    for line in lines:
        new_lines.append(line)
        for m in _FIG_REF_RE.finditer(line):
            num = m.group(1)
            if num in figs_to_embed and num not in inserted:
                img_path = fig_map[num]
                new_lines.append(f"\n![[{img_path.name}]]\n")
                inserted.add(num)

    return "\n".join(new_lines), len(inserted)


def _simplify_journal(journal: str) -> str:
    """将过长的期刊/会议名称简化为简称。"""
    if not journal:
        return ""
    # 常见会议简称映射
    short_names = {
        "Proceedings of the 31st ACM SIGKDD": "KDD",
        "Proceedings of the AAAI Conference": "AAAI",
        "International Conference on Learning Representations": "ICLR",
        "Neural Information Processing Systems": "NeurIPS",
        "International Conference on Machine Learning": "ICML",
        "International Joint Conference on Artificial Intelligence": "IJCAI",
        "The Web Conference": "WWW",
    }
    for prefix, short in short_names.items():
        if prefix.lower() in journal.lower():
            # 提取年份后缀（如 '25, 2025）
            year_match = re.search(r"'?\d{2,4}", journal)
            year_suffix = year_match.group(0) if year_match else ""
            return f"{short} {year_suffix}".strip()
    return journal


def _render_template(template: str, variables: dict[str, str]) -> str:
    """用正则匹配 {{key | filter}} 或 {{key}} 形式的占位符并替换。

    模板里可能包含 Obsidian/Templater 风格的占位符，例如：
      {{exportDate | format('YYYY-MM-DD')}}
      {{date | format('YYYY')}}
    我们只提取 key（忽略 filter），然后在 variables 中查找对应的值。
    """
    def replacer(match: re.Match) -> str:
        inner = match.group(1).strip()
        # 提取 key，忽略 filter（如 `date | format('YYYY')` 中的 key 是 `date`）
        key = inner.split("|")[0].strip()
        return variables.get(key, match.group(0))

    # 匹配 {{ ... }}，支持内部有单引号、空格和管道符
    pattern = re.compile(r"\{\{\s*(.+?)\s*\}\}")
    return pattern.sub(replacer, template)


def render_markdown(
    analysis: dict[str, Any],
    source_pdf: str,
    analysis_json: str,
    images_dir: str | Path | None = None,
    attachments_dir: str | Path | None = None,
) -> str:
    """根据分析 JSON 渲染 Obsidian Markdown。

    这个函数会把 LLM 的结构化结果，填入 `paper-note.md` 模板中。
    """
    template = load_template()
    title = analysis.get("title") or analysis.get("paper") or Path(source_pdf).stem

    # Authors: prefer YAML array for frontmatter
    authors_raw = analysis.get("authors", [])
    if isinstance(authors_raw, str):
        authors_raw = [a.strip() for a in authors_raw.split(",") if a.strip()]
    elif isinstance(authors_raw, list) and len(authors_raw) == 1 and isinstance(authors_raw[0], str) and "," in authors_raw[0]:
        # LLM 有时返回 ["A, B, C"] 而不是 ["A", "B", "C"]
        authors_raw = [a.strip() for a in authors_raw[0].split(",") if a.strip()]
    authors_yaml = _format_yaml_list(authors_raw)
    authors_str = ", ".join(str(a) for a in authors_raw) if authors_raw else ""

    year = str(analysis.get("year", ""))
    current_date = datetime.now().strftime("%Y-%m-%d")

    summary = _format_text(analysis.get("summary"))
    tldr = _format_text(analysis.get("tldr"))
    problem = _format_text(analysis.get("problem"))
    method = _format_text(analysis.get("method"))
    result = _format_text(analysis.get("result"))
    architecture = _format_text(analysis.get("architecture"))
    innovations = _format_bullets(analysis.get("innovations"))
    experiments = _format_text(analysis.get("experiments"))
    thoughts = _format_text(analysis.get("thoughts"))
    figure_notes = _format_bullets(analysis.get("figure_notes"))

    # 自动嵌入图片：扫描正文中的图号引用，复制到附件目录并插入引用
    _img_dir = Path(images_dir) if images_dir else None
    _att_dir = Path(attachments_dir) if attachments_dir else None
    architecture, _ = _embed_figure_images(architecture, _img_dir, _att_dir)
    experiments, _ = _embed_figure_images(experiments, _img_dir, _att_dir)
    limitations = _format_bullets(analysis.get("limitations"))

    # 优先使用原始摘要，如果没有则回退到 LLM 的 summary
    abstract_raw = analysis.get("abstract", "")
    # 清理 PDF 解析残留（如 "Jan\n" 前缀、断行 app-\nlications）
    abstract_cleaned = _clean_abstract(abstract_raw)
    abstract_display = abstract_cleaned if abstract_cleaned else summary

    variables = {
        "title": str(title),
        "authors": authors_str,
        "authors_yaml": authors_yaml,
        "publicationTitle": _simplify_journal(str(analysis.get("journal", ""))),
        "citekey": str(analysis.get("citekey", "")),
        "zoteroSelectURI": str(analysis.get("zotero_link", "")),
        "url": "",
        "source_pdf": "",
        "analysis_json": analysis_json,
        "date": year,
        "abstractNote": abstract_display,
        "tldr": tldr,
        "problem": problem,
        "method": method,
        "result": result,
        "architecture": architecture,
        "innovations": innovations,
        "experiments": experiments,
        "thoughts": thoughts,
        "figure_notes": figure_notes,
        "limitations": limitations,
        "desktopURI": "",
        "exportDate": current_date,
        "topics": _format_yaml_list(analysis.get("topics", [])),
        "aliases": _format_yaml_list(analysis.get("aliases", [])),
        "related_papers": _format_yaml_list(analysis.get("related_papers", [])),
    }
    return _render_template(template, variables)


def write_obsidian_note(
    analysis_json_path: str | Path,
    vault_dir: str | Path,
    note_name: str | None = None,
    images_dir: str | Path | None = None,
    attachments_dir: str | Path | None = None,
) -> ObsidianNote:
    """把 LLM 分析结果写进 Obsidian 笔记。

    参数说明：
    - analysis_json_path：`llm_analyzer.py` 的输出文件路径
    - vault_dir：你的 Obsidian Vault 根目录
    - note_name：可选，自定义笔记文件名；不填则根据论文标题自动生成
    - images_dir：可选，源图片目录路径；不填则自动从 analysis_json 同级目录推断
    - attachments_dir：可选，Obsidian 附件目录；图片会被复制到这里供 Obsidian 引用
    """
    analysis_json_path = Path(analysis_json_path)
    vault_dir = Path(vault_dir)
    vault_dir.mkdir(parents=True, exist_ok=True)

    analysis = load_json(analysis_json_path)
    source_pdf = str(analysis.get("paper", ""))

    # 推断图片目录
    if images_dir is None:
        candidate = analysis_json_path.parent / "images" / "png"
        if candidate.is_dir():
            images_dir = candidate

    markdown = render_markdown(
        analysis=analysis,
        source_pdf=source_pdf,
        analysis_json=str(analysis_json_path),
        images_dir=images_dir,
        attachments_dir=attachments_dir,
    )

    title = analysis.get("title") or analysis.get("paper") or analysis_json_path.stem
    safe_name = note_name or _slugify(str(title))
    note_path = vault_dir / f"{safe_name}.md"
    note_path.write_text(markdown, encoding="utf-8")

    return ObsidianNote(title=str(title), markdown=markdown, path=note_path)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Write LLM analysis into an Obsidian markdown note")
    parser.add_argument("input", type=Path, help="Input analysis JSON from tools/llm_analyzer.py")
    parser.add_argument("--vault", type=Path, required=True, help="Obsidian vault root directory")
    parser.add_argument("--name", type=str, default=None, help="Optional note filename without extension")
    parser.add_argument("--images-dir", type=Path, default=None, help="Directory containing extracted figure PNGs")
    parser.add_argument("--attachments-dir", type=Path, default=None, help="Obsidian attachments directory to copy images into")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    note = write_obsidian_note(args.input, args.vault, args.name, args.images_dir, args.attachments_dir)
    print(json.dumps({"title": note.title, "path": str(note.path)}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
